import { React, useState, useEffect } from "react";
import { FormFeild, Loader } from "../components/";

const Home = () => {
  const [loading, setLoading] = useState(true);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState();
  return (
    <section className="max-w-7x mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormFeild />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center item-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-meadium text-[]3666e75 text-xl mb-3">
                Showing results for
                <span className="text-[#222328">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:">

            </div>
            

          </>
        )}
      </div>
    </section>
  );
};

export default Home;
